-- MySQL Script generated by MySQL Workbench
-- 04/13/15 10:54:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema speakapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema speakapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `speakapp` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `speakapp` ;

-- -----------------------------------------------------
-- Table `speakapp`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`locations` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`locations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `state` VARCHAR(45) NULL,
  `street` VARCHAR(45) NULL,
  `zipcode` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`gender`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`gender` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`gender` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`users` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`profiles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`profiles` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`profiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `birthday` DATETIME NULL,
  `firstname` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `interests` TEXT NULL,
  `description` LONGTEXT NULL,
  `picture_url` VARCHAR(255) NULL,
  `picture_small_url` VARCHAR(255) NULL,
  `picture_big_url` VARCHAR(255) NULL,
  `hometown_location_id` INT NULL,
  `current_location_id` INT NULL,
  `gender_id` INT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `hometownLocation_idx` (`hometown_location_id` ASC),
  INDEX `currentLocation_idx` (`current_location_id` ASC),
  INDEX `profile_gender_fk_idx` (`gender_id` ASC),
  CONSTRAINT `hometownLocation_fk`
    FOREIGN KEY (`hometown_location_id`)
    REFERENCES `speakapp`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `currentLocation_fk`
    FOREIGN KEY (`current_location_id`)
    REFERENCES `speakapp`.`locations` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profile_gender_fk`
    FOREIGN KEY (`gender_id`)
    REFERENCES `speakapp`.`gender` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id_fk`
    FOREIGN KEY (`id`)
    REFERENCES `speakapp`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`languages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`languages` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `code` VARCHAR(5) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`profile_language_spoken`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`profile_language_spoken` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`profile_language_spoken` (
  `profile_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  INDEX `id_language_fk_idx` (`language_id` ASC),
  CONSTRAINT `id_profile_language_spoken_fk`
    FOREIGN KEY (`profile_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_language_language_spoken_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `speakapp`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`discussion_method`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`discussion_method` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`discussion_method` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`discussion_method_profile`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`discussion_method_profile` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`discussion_method_profile` (
  `id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`, `profile_id`),
  INDEX `id_profile_fk_idx` (`profile_id` ASC),
  CONSTRAINT `id_profile_discussion_method_fk`
    FOREIGN KEY (`profile_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_discussion_method_fk`
    FOREIGN KEY (`id`)
    REFERENCES `speakapp`.`discussion_method` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`status` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`status` (
  `code` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`relationship`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`relationship` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`relationship` (
  `status` INT NOT NULL,
  `profile_one_id` INT NOT NULL,
  `profile_two_id` INT NOT NULL,
  `action_user_id` INT NOT NULL,
  PRIMARY KEY (`profile_one_id`, `profile_two_id`),
  INDEX `profile_two_id_fk_idx` (`profile_two_id` ASC),
  INDEX `action_user_id_fk_idx` (`action_user_id` ASC),
  INDEX `status_id_fk_idx` (`status` ASC),
  CONSTRAINT `profile_one_id_fk`
    FOREIGN KEY (`profile_one_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `profile_two_id_fk`
    FOREIGN KEY (`profile_two_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `action_user_id_fk`
    FOREIGN KEY (`action_user_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `status_id_fk`
    FOREIGN KEY (`status`)
    REFERENCES `speakapp`.`status` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`profile_language_to_learn`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`profile_language_to_learn` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`profile_language_to_learn` (
  `profile_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  INDEX `id_language_fk_idx` (`language_id` ASC),
  CONSTRAINT `id_profile_language_to_learn_fk`
    FOREIGN KEY (`profile_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_language_language_to_learn_fk`
    FOREIGN KEY (`language_id`)
    REFERENCES `speakapp`.`languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `speakapp`.`chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `speakapp`.`chat` ;

CREATE TABLE IF NOT EXISTS `speakapp`.`chat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `message` TEXT NOT NULL,
  `sent_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_profile_fk_idx` (`profile_id` ASC),
  CONSTRAINT `id_profile_chat_fk`
    FOREIGN KEY (`profile_id`)
    REFERENCES `speakapp`.`profiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
